language: python
python: 3.6
sudo: required
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip && sudo unzip chromedriver_linux64.zip -d /usr/local/bin/ && rm -f chromedriver_linux64.zip
  - pip install selenium
install: true
script: python tests.py
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
